/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_asterix;

import java.io.IOException;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pergaixj
 */
public class V_Divinite extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Divinite.class.getName());

    private LinkedHashMap<Integer, M_divinites> lesDivinites;
    private M_divinites unDieu;
    private Integer ligne, iDivi;
   private DefaultTableModel dm_tb_Divinites;
    private C_asterix controler;
    /**
     * Creates new form V_Divinite
     */
    public V_Divinite(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private void activation(boolean actif) {
        tx_id.setEditable(false);
        tx_nom.setEditable(actif);
        tx_com.setEditable(actif);
       

    }
    public void clear() {
        tx_id.setText("");
        tx_nom.setText("");
        tx_com.setText("");
        tx_con.setText("");
        
    }
    private void sePlacer() {
        iDivi = table_divinite.getSelectedRow();

        int id = (Integer) table_divinite.getValueAt(iDivi, 0);

        unDieu = lesDivinites.get(id);
        tx_id.setText(String.valueOf(unDieu.getId()));
        tx_nom.setText(unDieu.getNom());
        tx_com.setText(unDieu.getCommentaire());
        tx_con.setText(unDieu.getContexte());
  }

    private void ihm(char mode) {
        if (mode == 'T') {
            jpan_divi.setVisible(true);
            bt_detail.setVisible(true);
        } else {
            switch (mode) {
                case 'C' -> {
                    lb_titre.setText("Consultationner");
                    this.activation(false);
                    jpan_divi.setVisible(false);
                    this.setSize(560, 400);
                    sePlacer();
                    bt_detail.setVisible(true);
                    bt_retour.setVisible(true);

                    bt_modif.setVisible(false);
                    bt_annuler.setVisible(false);
                }
                case 'A' -> {
                    lb_titre.setText("Ajoutationner");
                    this.activation(true);
                    jpan_divi.setVisible(false);
                    this.setSize(560, 400);
                    bt_detail.setVisible(true);
                    bt_enre.setVisible(true);
                    bt_annuler.setVisible(true);
                    bt_retour.setVisible(false);
                    clear();
                }
                case 'M' -> {
                    lb_titre.setText("Modificationner");
                    this.activation(true);
                    jpan_divi.setVisible(false);
                    this.setSize(560, 400);
                    sePlacer();
                    bt_detail.setVisible(true);
                    bt_enre.setVisible(true);
                    bt_annuler.setVisible(true);
                    bt_retour.setVisible(false);
                }

            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan_divi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_divinite = new javax.swing.JTable();
        bt_detail = new javax.swing.JButton();
        bt_modif = new javax.swing.JButton();
        bt_supp = new javax.swing.JButton();
        bt_ajout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_titre = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        lb_com = new javax.swing.JLabel();
        tx_id = new javax.swing.JTextField();
        tx_nom = new javax.swing.JTextField();
        tx_com = new javax.swing.JTextField();
        bt_enre = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        bt_retour = new javax.swing.JButton();
        lb_con = new javax.swing.JLabel();
        tx_con = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_divinite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Divinite"
            }
        ));
        table_divinite.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                table_divinitePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(table_divinite);

        bt_detail.setText("Detail");
        bt_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_detailActionPerformed(evt);
            }
        });

        bt_modif.setText("Modifier");
        bt_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifActionPerformed(evt);
            }
        });

        bt_supp.setText("Supprimer");
        bt_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suppActionPerformed(evt);
            }
        });

        bt_ajout.setText("Ajouter");
        bt_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpan_diviLayout = new javax.swing.GroupLayout(jpan_divi);
        jpan_divi.setLayout(jpan_diviLayout);
        jpan_diviLayout.setHorizontalGroup(
            jpan_diviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_diviLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jpan_diviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jpan_diviLayout.setVerticalGroup(
            jpan_diviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_diviLayout.createSequentialGroup()
                .addGroup(jpan_diviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_diviLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_diviLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bt_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        lb_id.setText("id :");

        lb_nom.setText("nom :");

        lb_com.setText("commentaire :");

        bt_enre.setText("Enregistrer");
        bt_enre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enreActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        bt_retour.setText("Retour");
        bt_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retourActionPerformed(evt);
            }
        });

        lb_con.setText("contexte :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tx_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(229, 229, 229))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_com, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tx_com, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_enre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_con, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_con, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_id))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_com, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_com, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_con, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tx_con, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpan_divi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpan_divi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_divinitePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_table_divinitePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_table_divinitePropertyChange

    private void bt_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_detailActionPerformed

        if (table_divinite.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "un personnage doit être sélectionné dans le tableau", "Sélection obligatoire", JOptionPane.ERROR_MESSAGE);
        } else {
            this.ihm('C');
        }

    }//GEN-LAST:event_bt_detailActionPerformed

    private void bt_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifActionPerformed
        if (table_divinite.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "un personnage doit être sélectionné dans le tableau", "Sélection obligatoire", JOptionPane.ERROR_MESSAGE);
        } else {
            this.ihm('M');
        }
    }//GEN-LAST:event_bt_modifActionPerformed

    private void bt_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suppActionPerformed
        if (table_divinite.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "une divinité doit être sélectionné dans le tableau", "Sélection obligatoire", JOptionPane.ERROR_MESSAGE);
    } else {
        iDivi = table_divinite.getSelectedRow();
        int id = (Integer) table_divinite.getValueAt(iDivi, 0);  // ← L'ID est ici !
        
        int reponse = JOptionPane.showConfirmDialog(this,
            "Êtes-vous sûr de vouloir supprimer la divinité ?",
            "Attention !",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (reponse == JOptionPane.YES_OPTION) {
            try {
                controler.supp_divi(id);  // ✅ Passer id, pas iDivi !
            } catch (java.sql.SQLException ex) {
                System.getLogger(V_Divinite.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }
    }//GEN-LAST:event_bt_suppActionPerformed

    private void bt_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajoutActionPerformed
        this.ihm('A');
    }//GEN-LAST:event_bt_ajoutActionPerformed

    private void bt_enreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enreActionPerformed
        String vNom = tx_nom.getText().trim();
    String vCom = tx_com.getText().trim();
    String vCon = tx_con.getText().trim();

    if (vNom.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Le nom est obligatoire.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean isModif = "Modificationner".equals(lb_titre.getText());

    if (isModif) {
        int vidPerso = Integer.parseInt(tx_id.getText());

        int reponse = JOptionPane.showConfirmDialog(
            this,
            "Êtes-vous sûr de vouloir modifier " + vNom + " ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (reponse == JOptionPane.YES_OPTION) {
            try {
                controler.enregistrer_divi(vidPerso, vNom, vCom, vCon);
                afficher(controler, lesDivinites);
            } catch (java.sql.SQLException ex) {
                JOptionPane.showMessageDialog(this,
                    "Erreur lors de la modification : " + ex.getMessage(),
                    "Erreur SQL/IO",
                    JOptionPane.ERROR_MESSAGE);
                logger.log(java.util.logging.Level.SEVERE, ex.getMessage(), ex);
            } catch (IOException ex) {
                System.getLogger(V_Divinite.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    } else {
        int reponse = JOptionPane.showConfirmDialog(
            this,
            "Êtes-vous sûr de vouloir ajouter " + vNom + " ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (reponse == JOptionPane.YES_OPTION) {
            try {
                controler.ajouter_divi(vNom, vCom, vCon);
                afficher(controler, lesDivinites);
            } catch (IOException ex) {
                System.getLogger(V_Divinite.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (java.sql.SQLException ex) {
                System.getLogger(V_Divinite.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    } 
    }//GEN-LAST:event_bt_enreActionPerformed

    /**
     *
     * @param gestionPerso
     * @param lesDivinites
     */
    
    public void afficher(C_asterix gestionPerso, LinkedHashMap<Integer, M_divinites> lesDivinites) {
        this.lesDivinites = lesDivinites;
        this.controler = gestionPerso;

        dm_tb_Divinites = (DefaultTableModel) table_divinite.getModel();
        dm_tb_Divinites.setRowCount(lesDivinites.size());
        ligne = 0;

        
        for (Integer uneCle : lesDivinites.keySet()) {
            unDieu = lesDivinites.get(uneCle);
            table_divinite.setValueAt(unDieu.getId(), ligne, 0);
            table_divinite.setValueAt(unDieu.getNom(), ligne, 1);
           
            ligne++;
            
        }
        
       

        this.setSize(600, 400);
        this.setLocationRelativeTo(null);

        bt_detail.setVisible(true);
        jpan_divi.setVisible(true);
        this.ihm('T');
        
        
        setVisible(true);
    }
    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        this.setSize(600, 500);
        this.setLocationRelativeTo(null);

        
        bt_detail.setVisible(true);
        jpan_divi.setVisible(true);
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void bt_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retourActionPerformed
        this.setSize(600, 500);
        this.setLocationRelativeTo(null);

        

        bt_detail.setVisible(true);
        bt_modif.setVisible(true);
        jpan_divi.setVisible(true);
    }//GEN-LAST:event_bt_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                V_Divinite dialog = new V_Divinite(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ajout;
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_detail;
    private javax.swing.JButton bt_enre;
    private javax.swing.JButton bt_modif;
    private javax.swing.JButton bt_retour;
    private javax.swing.JButton bt_supp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpan_divi;
    private javax.swing.JLabel lb_com;
    private javax.swing.JLabel lb_con;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JTable table_divinite;
    private javax.swing.JTextField tx_com;
    private javax.swing.JTextField tx_con;
    private javax.swing.JTextField tx_id;
    private javax.swing.JTextField tx_nom;
    // End of variables declaration//GEN-END:variables
}
