/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_asterix;

import java.sql.SQLException;

/**
 *
 * @author pergaixj
 */
public class V_main extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_main.class.getName());

    private C_asterix leControl;
    
    public void afficher() {
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        
        this.setVisible(true);
        
    }
    /**
     * Creates new form V_main
     */
    public V_main(C_asterix leControleur) {
        leControl = leControleur;
        initComponents();
    }

    private V_main() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mb_fichier = new javax.swing.JMenu();
        mi_quit = new javax.swing.JMenuItem();
        mb_asterix = new javax.swing.JMenu();
        mi_perso = new javax.swing.JMenuItem();
        mb_divinite = new javax.swing.JMenu();
        mi_divi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mb_fichier.setText("Fichier");

        mi_quit.setText("Quitter");
        mi_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_quitActionPerformed(evt);
            }
        });
        mb_fichier.add(mi_quit);

        menuBar.add(mb_fichier);

        mb_asterix.setText("asterix");

        mi_perso.setText("Personnage");
        mi_perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_persoActionPerformed(evt);
            }
        });
        mb_asterix.add(mi_perso);

        menuBar.add(mb_asterix);

        mb_divinite.setText("divinités");

        mi_divi.setText("Dieux");
        mi_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_diviActionPerformed(evt);
            }
        });
        mb_divinite.add(mi_divi);

        menuBar.add(mb_divinite);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_quitActionPerformed
        this.formWindowClosing(null);
        System.exit(0);
    }//GEN-LAST:event_mi_quitActionPerformed

    private void mi_persoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_persoActionPerformed
        try {
            leControl.aff_V_Personnage();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_persoActionPerformed

    private void mi_diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_diviActionPerformed
        try {
            leControl.aff_V_Divinite();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_diviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mb_asterix;
    private javax.swing.JMenu mb_divinite;
    private javax.swing.JMenu mb_fichier;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mi_divi;
    private javax.swing.JMenuItem mi_perso;
    private javax.swing.JMenuItem mi_quit;
    // End of variables declaration//GEN-END:variables

   private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        try {
            // TODO add your handling code here:

            leControl.deconnexion();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    } 
}
